-- Create table for saree website newsletter leads
CREATE TABLE IF NOT EXISTS public.saree_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    email TEXT NOT NULL UNIQUE,
    source TEXT DEFAULT 'newsletter'::text
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.saree_leads ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts so visitors can sign up without logging in
CREATE POLICY "Allow anonymous inserts" 
ON public.saree_leads 
FOR INSERT 
TO anon 
WITH CHECK (true);
